name: NPM publish CD workflow

on:
  release:
    types: [prereleased]

jobs:
  publish_npm:
    name: Publish on npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      # install Node.js
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      # set up git since we will later push to the repo
      - run: git config --global user.name "Haidang666"
      - run: git config --global user.email "hdcompany123@gmail.com"
      - run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
      # publish to NPM -> there is one caveat, continue reading for the fix
      - run: npm publish --tag ${{ github.event.release.target_commitish }}
        env:
          # Use a token to publish to NPM. See below for how to set it up
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # push the version changes to GitHub
      # - run: git push
      #   env:
      #     # The secret is passed automatically. Nothing to configure.
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
